* visfilt - Visual filtering library

  This is a generic library for visually filtering elements. Elements can be
  items of a list or lines of a buffer. 

  It is heavily influenced by eassist.el from [[http://cedet.sourceforge.net/][CEDET]]. The goal is to have
  similar user interface as eassist for lists and other filterable items,
  because eassist is specific to function/method names received from semantic.

  For example it can filter down recentf-list and open the selected
  file. Filtering happens by first displaying a screenful of elements from the
  list. From this point you can type a string that will be searched for in the
  list. The view is updated each time a new character is typed. You can select
  the wanted file name with RET and the file will be opened.

  This functionality is also very similar to [[https://github.com/emacs-helm/helm][emacs-helm]].

** What can it do ?

   The library contains the main function *visfilt*, which is the generic core
   functionality. There is a macro *visfilt-command-create* which is used to
   create interactive function wrappers for *visfilt*.

   Interactive functions are the following:

   - *visfilt-command-buffer-list*: Switches to a buffer.
   - *visfilt-command-recentf-list*: Opens a file from recentf-list.
   - *visfilt-command-occur*: Jump to a line in the current buffer similar to occur.


** Installation

   Clone the repository and load the library. Bind the wanted
   functions to keys.

   If you use [[https://github.com/dimitri/el-get][el-get]], you can use the following or similar recipe to install
   this:

#+BEGIN_SRC emacs-lisp
  (:name visfilt :type github :pkgname "kopoli/visfilt")
#+END_SRC

